type: S3
config:
  bucket: "${metrics_bucket}"
  endpoint: "${s3_endpoint}"
  region: ""
  access_key: ""
  insecure: false
  signature_version2: false
  secret_key: ""
  put_user_metadata: { "X-Amz-Acl": "bucket-owner-full-control" }
  http_config:
    idle_conn_timeout: 1m30s
    response_header_timeout: 2m
    insecure_skip_verify: false
  trace:
    enable: false
  list_objects_version: ""
  part_size: 134217728
  sse_config:
    type: "SSE-KMS"
    kms_key_id: "${kms_key_id}"
    kms_encryption_context: {}
    encryption_key: ""
