groups:
- name: alert.rules
  rules:
  - alert: MetadataNoToken
    annotations:
      message: IMDSv1 has been left enabled, please disable.
    expr: aws_ec2_metadata_no_token_maximum > 0
    for: 0s
    labels:
      severity: warning
