global:
  external_labels:
    role: ${environment}
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m

scrape_configs:
  - job_name: concourse-metrics
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    ec2_sd_configs:
      - endpoint: ""
        region: eu-west-2
        refresh_interval: 1m
        port: 9090
        filters: []
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        separator: ;
        regex: ^ci-concourse-web-[a-z0-9]{8}$
        replacement: $1
        action: keep
      - source_labels: [__meta_ec2_tag_Name, __meta_ec2_availability_zone]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
  - job_name: "ecs-service-discovery"
    scrape_interval: 1m
    file_sd_configs:
      - files:
          - /prometheus/ecs/1m-tasks.json
    relabel_configs:
      - source_labels: [metrics_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
  - job_name: global-node-exporter
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    ec2_sd_configs:
      - endpoint: ""
        region: eu-west-2
        refresh_interval: 1m
        port: 9100
        filters: []
    relabel_configs:
      - source_labels: [__meta_ec2_tag_aws_elasticmapreduce_instance_group_role]
        regex: "MASTER|CORE"
        replacement: $1
        action: drop
      - source_labels: [__meta_ec2_tag_Name]
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
  - job_name: emr-node-exporter
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    ec2_sd_configs:
      - endpoint: ""
        region: eu-west-2
        refresh_interval: 1m
        port: 9100
        filters: []
    relabel_configs:
      - source_labels: [__meta_ec2_tag_aws_elasticmapreduce_instance_group_role]
        regex: "MASTER|CORE"
        replacement: $1
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
  - job_name: jmx-hdfs-namenode
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    ec2_sd_configs:
      - endpoint: ""
        region: eu-west-2
        refresh_interval: 1m
        port: 7101
        filters: []
    relabel_configs:
      - source_labels: [__meta_ec2_tag_aws_elasticmapreduce_instance_group_role]
        regex: "MASTER|CORE"
        replacement: $1
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
  - job_name: jmx-hdfs-datanode
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    ec2_sd_configs:
      - endpoint: ""
        region: eu-west-2
        refresh_interval: 1m
        port: 7103
        filters: []
    relabel_configs:
      - source_labels: [__meta_ec2_tag_aws_elasticmapreduce_instance_group_role]
        regex: "MASTER|CORE"
        replacement: $1
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
  - job_name: jmx-yarn-resource-manager
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    ec2_sd_configs:
      - endpoint: ""
        region: eu-west-2
        refresh_interval: 1m
        port: 7105
        filters: []
    relabel_configs:
      - source_labels: [__meta_ec2_tag_aws_elasticmapreduce_instance_group_role]
        regex: "MASTER|CORE"
        replacement: $1
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace
  - job_name: jmx-yarn-node-manager
    honor_timestamps: true
    scrape_interval: 1m
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    ec2_sd_configs:
      - endpoint: ""
        region: eu-west-2
        refresh_interval: 1m
        port: 7107
        filters: []
    relabel_configs:
      - source_labels: [__meta_ec2_tag_aws_elasticmapreduce_instance_group_role]
        regex: "MASTER|CORE"
        replacement: $1
        action: keep
      - source_labels: [__meta_ec2_tag_Name]
        regex: (.*)
        target_label: instance
        replacement: $1
        action: replace

remote_write:
  - url: http://localhost:10903/api/v1/receive
