
exporter_port: 3392
log_level: info
metrics_bucket: ${metrics_bucket}
metrics_key: ${metrics_key}
metric_name_prefix: pdm
metrics:
- name: buffers_direct_capacity
  path: $.gauges.'buffers.direct.capacity'.value
- name: buffers_direct_count
  path: $.gauges.'buffers.direct.count'.value
- name: buffers_direct_used
  path: $.gauges.'buffers.direct.used'.value
- name: buffers_mapped_capacity
  path: $.gauges.'buffers.mapped.capacity'.value
- name: buffers_mapped_count
  path: $.gauges.'buffers.mapped.count'.value
- name: buffers_mapped_used
  path: $.gauges.'buffers.mapped.used'.value
- name: classLoading_loaded
  path: $.gauges.'classLoading.loaded'.value
- name: classLoading_unloaded
  path: $.gauges.'classLoading.unloaded'.value
- name: gc_PS_MarkSweep_count
  path: $.gauges.'gc.PS-MarkSweep.count'.value
- name: gc_PS_MarkSweep_time
  path: $.gauges.'gc.PS-MarkSweep.time'.value
- name: gc_PS_Scavenge_count
  path: $.gauges.'gc.PS-Scavenge.count'.value
- name: gc_PS_Scavenge_time
  path: $.gauges.'gc.PS-Scavenge.time'.value
- name: memory_heap_committed
  path: $.gauges.'memory.heap.committed'.value
- name: memory_heap_init
  path: $.gauges.'memory.heap.init'.value
- name: memory_heap_max
  path: $.gauges.'memory.heap.max'.value
- name: memory_heap_usage
  path: $.gauges.'memory.heap.usage'.value
- name: memory_heap_used
  path: $.gauges.'memory.heap.used'.value
- name: memory_non_heap_committed
  path: $.gauges.'memory.non-heap.committed'.value
- name: memory_non_heap_init
  path: $.gauges.'memory.non-heap.init'.value
- name: memory_non_heap_max
  path: $.gauges.'memory.non-heap.max'.value
- name: memory_non_heap_usage
  path: $.gauges.'memory.non-heap.usage'.value
- name: memory_non_heap_used
  path: $.gauges.'memory.non-heap.used'.value
- name: memory_pools_Code_Cache_usage
  path: $.gauges.'memory.pools.Code-Cache.usage'.value
- name: memory_pools_Compressed_Class_Space_usage
  path: $.gauges.'memory.pools.Compressed-Class-Space.usage'.value
- name: memory_pools_Metaspace_usage
  path: $.gauges.'memory.pools.Metaspace.usage'.value
- name: memory_pools_PS_Eden_Space_usage
  path: $.gauges.'memory.pools.PS-Eden-Space.usage'.value
- name: memory_pools_PS_Old_Gen_usage
  path: $.gauges.'memory.pools.PS-Old-Gen.usage'.value
- name: memory_pools_PS_Survivor_Space_usage
  path: $.gauges.'memory.pools.PS-Survivor-Space.usage'.value
- name: memory_total_committed
  path: $.gauges.'memory.total.committed'.value
- name: memory_total_init
  path: $.gauges.'memory.total.init'.value
- name: memory_total_max
  path: $.gauges.'memory.total.max'.value
- name: memory_total_used
  path: $.gauges.'memory.total.used'.value
- name: threads_blocked_count
  path: $.gauges.'threads.blocked.count'.value
- name: threads_count
  path: $.gauges.'threads.count'.value
- name: threads_daemon_count
  path: $.gauges.'threads.daemon.count'.value
- name: threads_deadlock_count
  path: $.gauges.'threads.deadlock.count'.value
- name: threads_new_count
  path: $.gauges.'threads.new.count'.value
- name: threads_runnable_count
  path: $.gauges.'threads.runnable.count'.value
- name: threads_terminated_count
  path: $.gauges.'threads.terminated.count'.value
- name: threads_timed_waiting_count
  path: $.gauges.'threads.timed_waiting.count'.value
- name: threads_waiting_count
  path: $.gauges.'threads.waiting.count'.value
- name: runtime_step_1create_hive_dynamo_table
  path: $.gauges.'runtime_step_1create-hive-dynamo-table'.value
- name: runtime_step_2metrics_setup
  path: $.gauges.'runtime_step_2metrics-setup'.value
- name: runtime_step_3clean_dictionary_data
  path: $.gauges.'runtime_step_3clean_dictionary_data'.value
- name: runtime_step_4create_db
  path: $.gauges.'runtime_step_4create_db'.value
- name: runtime_step_5intial_transactional_load
  path: $.gauges.'runtime_step_5intial_transactional_load'.value
- name: runtime_step_6transactional
  path: $.gauges.'runtime_step_6transactional'.value
- name: runtime_step_7source
  path: $.gauges.'runtime_step_7source'.value
- name: runtime_step_8transform
  path: $.gauges.'runtime_step_8transform'.value
- name: runtime_step_9model
  path: $.gauges.'runtime_step_9model'.value
- name: runtime_step_10views
  path: $.gauges.'runtime_step_10views'.value
- name: runtime_step_11create_pii_csv_files
  path: $.gauges.'runtime_step_11create_pii_csv_files'.value
- name: runtime_step_12row_count
  path: $.gauges.'runtime_step_12row-count'.value
- name: rowcount_uc_pdm_transform
  path: $.gauges.'rowcount_uc_pdm_transform'.value
- name: rowcount_uc_pdm_transactional
  path: $.gauges.'rowcount_uc_pdm_transactional'.value
- name: rowcount_uc_pdm_model
  path: $.gauges.'rowcount_uc_pdm_model'.value
- name: rowcount_uc
  path: $.gauges.'rowcount_uc'.value
- name: state_step_1create_hive_dynamo_table
  path: $.gauges.'state_step_1create-hive-dynamo-table'.value
- name: state_step_2metrics_setup
  path: $.gauges.'state_step_2metrics-setup'.value
- name: state_step_3clean_dictionary_data
  path: $.gauges.'state_step_3clean_dictionary_data'.value
- name: state_step_4create_db
  path: $.gauges.'state_step_4create_db'.value
- name: state_step_5intial_transactional_load
  path: $.gauges.'state_step_5intial_transactional_load'.value
- name: state_step_6transactional
  path: $.gauges.'state_step_6transactional'.value
- name: state_step_7source
  path: $.gauges.'state_step_7source'.value
- name: state_step_8transform
  path: $.gauges.'state_step_8transform'.value
- name: state_step_9model
  path: $.gauges.'state_step_9model'.value
- name: state_step_10views
  path: $.gauges.'state_step_10views'.value
- name: state_step_11create_pii_csv_files
  path: $.gauges.'state_step_11create_pii_csv_files'.value
- name: runtime_step_12row_count
  path: $.gauges.'runtime_step_12row-count'.value
