
exporter_port: 3392
log_level: info
metrics_bucket: ${metrics_bucket}
metrics_key: ${metrics_key}
metric_name_prefix: pdm_hive
metrics:
- name: buffers_direct_capacity
  path: $.gauges.'buffers.direct.capacity'.value
- name: buffers_direct_count
  path: $.gauges.'buffers.direct.count'.value
- name: buffers_direct_used
  path: $.gauges.'buffers.direct.used'.value
- name: buffers_mapped_capacity
  path: $.gauges.'buffers.mapped.capacity'.value
- name: buffers_mapped_count
  path: $.gauges.'buffers.mapped.count'.value
- name: buffers_mapped_used
  path: $.gauges.'buffers.mapped.used'.value
- name: class_loading_loaded
  path: $.gauges.'classLoading.loaded'.value
- name: class_loading_unloaded
  path: $.gauges.'classLoading.unloaded'.value
- name: gc_concurrent_mark_sweep_count
  path: $.gauges.'gc.ConcurrentMarkSweep.count'.value
- name: gc_concurrent_mark_sweep_time
  path: $.gauges.'gc.ConcurrentMarkSweep.time'.value
- name: gc_par_new_count
  path: $.gauges.'gc.ParNew.count'.value
- name: gc_par_new_time
  path: $.gauges.'gc.ParNew.time'.value
- name: init_total_count_dbs
  path: $.gauges.'init_total_count_dbs'.value
- name: init_total_count_partitions
  path: $.gauges.'init_total_count_partitions'.value
- name: init_total_count_tables
  path: $.gauges.'init_total_count_tables'.value
- name: memory_heap_committed
  path: $.gauges.'memory.heap.committed'.value
- name: memory_heap_init
  path: $.gauges.'memory.heap.init'.value
- name: memory_heap_max
  path: $.gauges.'memory.heap.max'.value
- name: memory_heap_usage
  path: $.gauges.'memory.heap.usage'.value
- name: memory_heap_used
  path: $.gauges.'memory.heap.used'.value
- name: memory_non_heap_committed
  path: $.gauges.'memory.non-heap.committed'.value
- name: memory_non_heap_init
  path: $.gauges.'memory.non-heap.init'.value
- name: memory_non_heap_max
  path: $.gauges.'memory.non-heap.max'.value
- name: memory_non_heap_usage
  path: $.gauges.'memory.non-heap.usage'.value
- name: memory_non_heap_used
  path: $.gauges.'memory.non-heap.used'.value
- name: memory_pools_cms_old_gen_usage
  path: $.gauges.'memory.pools.CMS-Old-Gen.usage'.value
- name: memory_pools_code_cache_usage
  path: $.gauges.'memory.pools.Code-Cache.usage'.value
- name: memory_pools_compressed_class_space_usage
  path: $.gauges.'memory.pools.Compressed-Class-Space.usage'.value
- name: memory_pools_metaspace_usage
  path: $.gauges.'memory.pools.Metaspace.usage'.value
- name: memory_pools_par_eden_space_usage
  path: $.gauges.'memory.pools.Par-Eden-Space.usage'.value
- name: memory_pools_par_survivor_space_usage
  path: $.gauges.'memory.pools.Par-Survivor-Space.usage'.value
- name: memory_total_committed
  path: $.gauges.'memory.total.committed'.value
- name: memory_total_init
  path: $.gauges.'memory.total.init'.value
- name: memory_total_max
  path: $.gauges.'memory.total.max'.value
- name: memory_total_used
  path: $.gauges.'memory.total.used'.value
- name: threads_blocked_count
  path: $.gauges.'threads.blocked.count'.value
- name: threads_count
  path: $.gauges.'threads.count'.value
- name: threads_daemon_count
  path: $.gauges.'threads.daemon.count'.value
- name: threads_deadlock_count
  path: $.gauges.'threads.deadlock.count'.value
- name: threads_new_count
  path: $.gauges.'threads.new.count'.value
- name: threads_runnable_count
  path: $.gauges.'threads.runnable.count'.value
- name: threads_terminated_count
  path: $.gauges.'threads.terminated.count'.value
- name: threads_timed_waiting_count
  path: $.gauges.'threads.timed_waiting.count'.value
- name: threads_waiting_count
  path: $.gauges.'threads.waiting.count'.value
