jobs:
  - name: integration
    plan:
      - get: dataworks-metrics-infrastructure
        passed:
          - qa
        trigger: true
      - get: dataworks-dashboards

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: integration

      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: integration

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: integration
      - .: (( inject meta.plan.cycle-containers ))
        task: trigger-prometheus-deployment
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
          CLUSTER: metrics
          SERVICE: prometheus
