jobs:
  - name: management-dev
    plan:
      - get: dataworks-metrics-infrastructure
        trigger: true
      - get: dataworks-dashboards
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
            TF_WORKSPACE: management-dev
      - .: (( inject meta.plan.terraform-apply ))
        params:
            TF_WORKSPACE: management-dev
      - .: (( inject meta.plan.terraform-plan ))
        params:
            TF_WORKSPACE: management-dev
