jobs:
  - name: management
    plan:
      - get: dataworks-metrics-infrastructure
        passed:
          - management-dev
        trigger: true
      - get: dataworks-dashboards
        passed:
          - management-dev
        trigger: true

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: management
          AWS_SECRETS_ROLE: arn:aws:iam::((aws_account.management)):role/ci

      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: management

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: management
      - .: (( inject meta.plan.cycle-containers ))
        task: trigger-outofband-deployment
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          CLUSTER: main
          SERVICE: outofband

      - .: (( inject meta.plan.cycle-containers ))
        task: trigger-prometheus-deployment
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          CLUSTER: main
          SERVICE: prometheus
