jobs:
  - name: management-dev
    plan:
      - get: dataworks-metrics-infrastructure
        trigger: true
      - get: dataworks-dashboards
        trigger: true

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: management-dev

      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: management-dev

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: management-dev
      - .: (( inject meta.plan.cycle-containers ))
        task: trigger-outofband-deployment
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci
          CLUSTER: metrics
          SERVICE: outofband

      - .: (( inject meta.plan.cycle-containers ))
        task: trigger-prometheus-deployment
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci
          CLUSTER: metrics
          SERVICE: prometheus
