jobs:
  - name: management
    max_in_flight: 1
    plan:
      - get: dw-al2-ecs-ami
        trigger: true
      - get: dataworks-metrics-infrastructure
        passed:
          - management-dev
        trigger: true
      - get: dataworks-dashboards
        passed:
          - management-dev
        trigger: true

      - .: (( inject meta.plan.create-credentials ))
        params:
          GRAFANA_USER: ((dataworks-secrets.grafana_user))
          GRAFANA_PASSWORD: ((dataworks-secrets.grafana_password))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci      

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: management
          AWS_SECRETS_ROLE: arn:aws:iam::((aws_account.management)):role/ci

      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: management

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: management
