jobs:
  - name: management-dev
    plan:
      - get: dw-al2-ecs-ami
      - get: dataworks-metrics-infrastructure
        trigger: true
      - get: dataworks-dashboards
        trigger: true

      - .: (( inject meta.plan.create-credentials ))
        params:
          GRAFANA_USER: ((dataworks-secrets.grafana_user_mgt_dev))
          GRAFANA_PASSWORD: ((dataworks-secrets.grafana_password_mgt_dev))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management-dev)):role/ci      

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: management-dev

      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: management-dev

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: management-dev
