jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - get: dw-al2-ecs-ami
      - get: dataworks-metrics-infrastructure
        passed:
          - integration
        trigger: true
      - get: dataworks-dashboards

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: preprod

      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: preprod

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: preprod
