jobs:
  - name: preprod
    plan:
      - get: dataworks-metrics-infrastructure
        passed:
          - integration
        trigger: true
      - get: dataworks-dashboards

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: preprod

      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: preprod

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: preprod
      - .: (( inject meta.plan.cycle-containers ))
        task: trigger-prometheus-deployment
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
          CLUSTER: metrics
          SERVICE: prometheus
