jobs:
  - name: production
    plan:
      - get: dataworks-metrics-infrastructure
        passed:
          - preprod
        trigger: true
      - get: dataworks-dashboards

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: production

      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: production

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: production
      - .: (( inject meta.plan.cycle-containers ))
        task: trigger-prometheus-deployment
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.production)):role/ci
          CLUSTER: main
          SERVICE: prometheus
