jobs:
- name: dataworks-metrics-infrastructure-pr
  plan:
  - get: dw-al2-ecs-ami
  - get: dataworks-metrics-infrastructure-pr
    trigger: true
    version: every
  - get: dataworks-dashboards
  - put: dataworks-metrics-infrastructure-pr
    params:
      path: dataworks-metrics-infrastructure-pr
      status: pending
  - .: (( inject meta.plan.terraform-bootstrap ))
    task: terraform-bootstrap-management
    input_mapping:
      dataworks-metrics-infrastructure: dataworks-metrics-infrastructure-pr
    params:
      TF_WORKSPACE: management
  - .: (( inject meta.plan.terraform-plan ))
    task: terraform-plan-management
    input_mapping:
      dataworks-metrics-infrastructure: dataworks-metrics-infrastructure-pr
    params:
      TF_WORKSPACE: management
    on_failure:
      put: dataworks-metrics-infrastructure-pr
      params:
        path: dataworks-metrics-infrastructure-pr
        status: failure
  - .: (( inject meta.plan.terraform-bootstrap ))
    task: terraform-bootstrap-qa
    input_mapping:
      dataworks-metrics-infrastructure: dataworks-metrics-infrastructure-pr
    params:
      TF_WORKSPACE: qa
  - .: (( inject meta.plan.terraform-plan ))
    task: terraform-plan-qa
    input_mapping:
      dataworks-metrics-infrastructure: dataworks-metrics-infrastructure-pr
    params:
      TF_WORKSPACE: qa
    on_failure:
      put: dataworks-metrics-infrastructure-pr
      params:
        path: dataworks-metrics-infrastructure-pr
        status: failure
    on_success:
      put: dataworks-metrics-infrastructure-pr
      params:
        path: dataworks-metrics-infrastructure-pr
        status: success
