jobs:
  - name: qa
    plan:
      - get: dataworks-metrics-infrastructure
        passed:
        - development
        trigger: true
      - get: dataworks-dashboards

      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: qa

      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: qa

      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: qa

      - .: (( inject meta.plan.cycle-containers ))
        task: trigger-prometheus-deployment
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
          CLUSTER: main
          SERVICE: prometheus

      - .: (( inject meta.plan.trigger-deployment ))
        task: trigger-cloudwatch-exporter-deployment
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.qa)):role/ci
          CLUSTER: main
          SERVICE: cloudwatch-exporter
