jobs:
  - name: qa
    plan:
      - get: dataworks-metrics-infrastructure
        passed:
        - development
        trigger: true
      - get: dataworks-dashboards
      - .: (( inject meta.plan.terraform-bootstrap ))
        params:
          TF_WORKSPACE: qa
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: qa
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: qa
