jobs:
  - name: cycle-outofband-management
    plan:
      - .: (( inject meta.plan.admin-enable ))
      - .: (( inject meta.plan.cycle-containers ))
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          CLUSTER: metrics
          SERVICE: outofband
  - name: redeploy-outofband-management
    plan:
      - .: (( inject meta.plan.admin-enable ))
      - .: (( inject meta.plan.trigger-deployment ))
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          CLUSTER: metrics
          SERVICE: outofband
