jobs:
  - name: mgmt-prometheus
    plan:
      - get: dataworks-metrics-infrastructure
        trigger: false
        passed:
          - production-prometheus
      - .: (( inject meta.plan.cycle-containers ))
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          CLUSTER: main
          SERVICE: prometheus
