jobs:
  - name: cycle-prometheus-preprod
    plan:
      - .: (( inject meta.plan.cycle-containers ))
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
          CLUSTER: main
          SERVICE: prometheus
