jobs:
  - name: cycle-hbase-exporter-development
    plan:
      - .: (( inject meta.plan.cycle-containers ))
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci
          CLUSTER: metrics
          SERVICE: hbase-exporter
