jobs:
  - name: cycle-hbase-exporter-preprod
    plan:
      - .: (( inject meta.plan.admin-enable ))
      - .: (( inject meta.plan.cycle-containers ))
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.preprod)):role/ci
          CLUSTER: metrics
          SERVICE: hbase-exporter
