static:
  - namespace: EMR/Collections
    name: collections
    regions:
      - ${region}
    metrics:
      - name: AllCollectionsProcessingTime
        statistics:
          - Minimum
        period: 60
        length: 300

  - namespace: AWS/EC2
    name: security
    regions:
      - ${region}
    metrics:
      - name: MetadataNoToken
        statistics:
          - Maximum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgFullFailed
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_full_failed
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgFullTerminated
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_full_terminated
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgFullSuccess
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_full_success
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgIncrementalFailed
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_incremental_failed
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgIncrementalTerminated
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_incremental_terminated
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: adgIncrementalSuccess
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: adg_incremental_success
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: pdmFailed
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: pdm_failed
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: pdmTerminated
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: pdm_terminated
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300

  - namespace: AWS/Events
    name: pdmSuccess
    regions:
      - ${region}
    dimensions:
      - name: RuleName
        value: pdm_success
    metrics:
      - name: TriggeredRules
        statistics:
          - Sum
        period: 60
        length: 300
