meta:
  plan:
    terraform-bootstrap:
      task: terraform-bootstrap
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: dwpdigital/jinja-yaml-aws
            version: 0.0.19
            tag: 0.0.19
        run:
          path: sh
          args:
            - -exc
            - |
              python bootstrap_terraform.py
              sed -i '/^assume_role/ d' terraform/deploy/terraform.tfvars
              cp terraform/deploy/terraform.tf ../terraform-config
              cp terraform/deploy/terraform.tfvars ../terraform-config
          dir: dataworks-metrics-infrastructure
        inputs:
          - name: dataworks-metrics-infrastructure
        outputs:
          - name: terraform-config
      params:
        AWS_REGION: eu-west-2
    terraform-apply:
      task: terraform-apply
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: hashicorp/terraform
            version: ((dataworks.terraform_version))
            tag: ((dataworks.terraform_version))
        run:
          path: sh
          args:
            - -exc
            - |
              cp ../../../terraform-config/terraform.tf .
              cp ../../../terraform-config/terraform.tfvars .
              terraform workspace show
              terraform init
              terraform plan -out terraform.plan
              terraform apply -auto-approve terraform.plan
          dir: dataworks-metrics-infrastructure/terraform/deploy
        inputs:
          - name: dataworks-metrics-infrastructure
          - name: terraform-config
      params:
        TF_CLI_ARGS_apply: -lock-timeout=300s
        TF_INPUT: "false"
    terraform-plan:
      task: terraform-plan
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: hashicorp/terraform
            version: ((dataworks.terraform_version))
            tag: ((dataworks.terraform_version))
        run:
          path: sh
          args:
            - -exc
            - |
              cp ../../../terraform-config/terraform.tf .
              cp ../../../terraform-config/terraform.tfvars .
              terraform workspace show
              terraform init
              terraform plan -detailed-exitcode
          dir: dataworks-metrics-infrastructure/terraform/deploy
        inputs:
          - name: dataworks-metrics-infrastructure
          - name: terraform-config
      params:
        TF_CLI_ARGS_plan: -lock-timeout=300s
        TF_INPUT: "false"
