jobs:
  - name: cycle-pdm-exporter-integration
    plan:
      - .: (( inject meta.plan.cycle-containers ))
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.integration)):role/ci
          CLUSTER: main
          SERVICE: pdm-exporter
