jobs:
  - name: cycle-thanos-query-management
    plan:
      - .: (( inject meta.plan.cycle-containers ))
        params:
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.management)):role/ci
          CLUSTER: main
          SERVICE: thanos-query
